BEGIN TRANSACTION
SELECT
	*
INTO #TempSet
FROM
(VALUES
('0A004598446'),
('0A004632010'),
('0A004883521'),
('0A004875906'),
('0B004605703'),
('0B004814887'),
('0G004730565'),
('0R004605675'),
('1G004869260'),
('1D004749045')
) List (allCMN)

SELECT * FROM CDP.F_SSN_multiENT WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM
SELECT * FROM CDP.X_NENT_by_SSN_max WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM
SELECT * FROM CDP.X_NENT_by_SSN_max_tp WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM
SELECT * FROM CDP.X_NENT_NSSN_max WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM
SELECT * FROM CDP.X_NENT_NSSN_max_tp WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM

--SELECT * FROM CDP.X_NSSN_SSNEnt_max_tp WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM
--SELECT * FROM CDP.F_SSN_multiENT WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM

SELECT matched_SSN, * FROM CDP.FS_PA_Matching_SSN WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM, I_NM_ADR

--SELECT * FROM CDP.FS_PA_Matching_SSN_UAT WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM
--SELECT * FROM CDP.FS_PA_Matching_SSN_UAT_old WHERE I_ALLCLM IN (SELECT allCMN FROM #TempSet) ORDER BY I_ALLCLM

ROLLBACK TRANSACTION

