SET NOEXEC OFF;

BEGIN TRANSACTION

GO
IF(@@TRANCOUNT <1 OR @@ERROR <> 0)
BEGIN
	ROLLBACK TRANSACTION;
	SET NOEXEC ON;
END
GO

USE ClaimSearch_Dev

CREATE TABLE dbo.FireMarshalContactList
(
	fmState CHAR(100) NOT NULL,
	firstName VARCHAR(100) NULL,
	middleName VARCHAR(100) NULL,
	lastName VARCHAR(100) NULL,
	suffixName VARCHAR(15) NULL,
	dept VARCHAR(100) NULL,
	div VARCHAR(100) NULL,
	fMDeliveryAddressLine1 VARCHAR(100) NOT NULL,
	fMDeliveryAddressLine2 VARCHAR(100) NULL,
	fMDeliveryCity VARCHAR(100) NOT NULL,
	fMDeliveryStateCode CHAR(2) NULL,
	zipCode VARCHAR(10) NOT NULL,
	title VARCHAR(50) NULL,
	salutation VARCHAR(15) NULL
);

INSERT INTO dbo.FireMarshalContactList
	(fmState, firstName, middleName, lastName, suffixName, dept, div, fMDeliveryAddressLine1, fMDeliveryAddressLine2, fMDeliveryCity, fMDeliveryStateCode, zipCode, title, salutation)
VALUES
	/*excelformula: ="("&IF(ISBLANK(A2),"NULL","'"&A2&"'")&", "&IF(ISBLANK(B2),"NULL","'"&B2&"'")&", "&IF(ISBLANK(C2),"NULL","'"&C2&"'")&", "&IF(ISBLANK(D2),"NULL",*/
	('AK', 'David', NULL, 'Tyler', NULL, 'DEPARTMENT OF PUBLIC SAFETY', 'DIVISION OF FIRE PREVENTION ', '5700 E, TUDOR ROAD', NULL, 'ANCHORAGE', 'AK', '99507', 'FIRE MARSHALL', 'MR'),
	/*NOTE: I removed 'CHIEF' from dept col for AZ*/('AZ', 'BOBBY', NULL, 'RUIZ', NULL, NULL, 'CITY OF PHOENIX FIRE DEPT', '520 W VAN BUREN AVE', NULL, 'PHOENIX', 'AZ', '85003', 'CHIEF', 'MR'), 
	('DE', 'GROVER', 'P', 'INGLE', NULL, 'OFFICE OF STATE FIRE MARSHAL', NULL, 'RD 2  BOX 166A', NULL, 'DOVER', 'DE', '19901', NULL, 'MR'),
	('GA', 'DOUGLAS', 'R', 'BURDICK', NULL, 'PROPERTY INSURANCE LOSS REGISTER', NULL, '700 NEW BRUNSWICK AVENUE', NULL, 'RAHWAY', 'NJ', '7065', NULL, 'MR'),
	('ID', 'DON', NULL, 'MC''COY', NULL, 'OFFICE OF THE STATE FIRE MARSHALL', 'DEPARTMENT OF INSURANCE', '700 WEST STATE STREET', NULL, 'BOISE', 'ID', '83720', NULL, 'MR'),
	('KS', 'GALE', NULL, 'HAAG', NULL, 'STATE FIRE MARSHAL', NULL, '700 SW JACKSON', 'SUITE 600', 'TOPEKA', 'KS', '66603-3714', NULL, 'MR'),
	('KY', 'DAVID', 'L', 'MANLEY', NULL, 'CHIEF DEPUTY FIRE MARSHAL', 'DEPARTMENT OF HOUSING', '127 OFFICE BUILDING', 'U.S. 127 SOUTH', 'FRANKFORT', 'KY', '40601', NULL, 'MR'),
	('MD', 'ROBERT', 'B', 'THOMAS', 'JR', 'DEPUTY CHIEF STATE FIRE MARSHAL', NULL, '1201 REISTERSTOWN ROAD', NULL, 'PIKESVILLE', 'MD', '21208-3899', NULL, 'MR'),
	('MA', 'JOSEPH', 'A', 'O''KEEFE', 'PE', 'OFFICE OF STATE FIRE MARSHAL', NULL, '1010 COMMONWEALTH AVENUE', NULL, 'BOSTON', 'MA', '2215', NULL, 'MR'),
	('MT', NULL, NULL, NULL, NULL, 'FIRE PREVENTION AND INVESTIGATION BUREAU', 'DEPARTMENT OF JUSTICE', 'P.O. BOX 201417', NULL, 'HELENA', NULL, '201417', NULL, NULL),
	('ND', 'ROBERT', NULL, 'ALLEN', NULL, 'OFFICE OF FIRE MARSHALL', NULL, '1929 NORTH WASHINGTON', 'NORTHBROOK MALL', 'BISMARK', 'ND', '58505', NULL, 'MR'),
	('NE', 'WALLACE', 'M', 'BARNETT', NULL, 'STATE FIRE MARSHALL', 'STATE FIRE MARSHAL''S OFFICE', 'P.O. BOX 94677', NULL, 'LINCOLN', 'NE', '68509', NULL, 'MR'),
	/*NOTE: I moved 'MARTEL' from suffixName to lastName for NH*/('NH', 'BARBARA', 'J', 'MARTEL', NULL, 'STATE FIRE MARSHAL', 'DEPARTMENT OF SAFETY', 'J. H. HAYES BUILDING', NULL, 'CONCORD', 'NH', '3301', NULL, 'MS'),
	('NM', 'JAMES', NULL, 'MAXON', NULL, 'FIRE INVESTIGATOR', NULL, '142 WEST PALACE 2ND FLOOR', 'BOKUM BUILDING INVESTIGATION DIV', 'SANTA FE', 'NM', '87501', NULL, 'MR'),
	('TN', NULL, NULL, NULL, NULL, 'STATE FIRE MARSHALL', NULL, '500 JAMES ROBERTSON PKWY', 'THIRD FLOOR, VOLUNTEER PLAZA', 'NASHVILLE', 'TN', '37219', NULL, 'SIR'),
	('VT', 'BRUCE', NULL, 'LANG', NULL, 'ASSISTANT DEPUTY FIRE MARSHAL', 'OFFICE OF STATE FIRE MARSHAL', 'DEPARTMENT OF PUBLIC SAFETY', '103 SOUTH MAIN STREET', 'WATERBURY', 'VT', '5676', 'LT', 'MR'),
	('WA', 'R', 'G', 'MARQUARDT', NULL, 'OFFICE OF INSURANCE COMMISSIONER AND STATE FIRE MARSHAL', NULL, 'INSURANCE BUILDING AQ-21', NULL, 'OLYMPIA', 'WA', '98504', 'COMMISSIONER', NULL),
	('WV', 'STERLING', NULL, 'LEWIS', 'JR', 'WV STATE FIRE COMMISSION', NULL, '1207 QUARRIER STREET ', 'SUITE 202', 'CHARLESTON', 'WV', '25301', NULL, 'MR');

SELECT * FROM dbo.FireMarshalContactList

GO
IF(@@TRANCOUNT <1 OR @@ERROR <> 0)
BEGIN
	ROLLBACK TRANSACTION;
	SET NOEXEC ON;
END
GO

PRINT 'ROLLBACK';ROLLBACK TRANSACTION;
--PRINT 'COMMIT';COMMIT TRANSACTION;
