BEGIN TRANSACTION
USE ClaimSearch_Dev
DECLARE @dateInserted DATE = GETDATE();
	
SELECT *
FROM DecisionNet.ProductGroup
UPDATE DecisionNet.ProductGroup
SET
	ProductGroup.productGroupName = ProductGroupUpdateSet.productGroupName
FROM
	(
		VALUES
			(1, 'People'),
			(2, 'Vehicle'),
			(6, 'Directory Assistance'),
			(7, 'Weather Reports'),
			(8, 'Criminal\Civil'),
			(9, 'Police Reports'),
			(10, 'Driver History'),
			(11, 'Medical Records'),
			(13, 'Other')
	) AS ProductGroupUpdateSet (productGroupId, productGroupName)
WHERE
	ProductGroup.productGroupId = ProductGroupUpdateSet.productGroupId
IF(NOT EXISTS
	(
		SELECT NULL
		FROM DecisionNet.ProductGroup
		WHERE ProductGroup.productGroupId IN (14,15,16,17)
	))
BEGIN
	INSERT INTO DecisionNet.ProductGroup
	(
		productGroupId,
		productGroupName,
		productGroupDescription
	)
	VALUES
		(14, 'Court Fees',NULL),
		(15, 'Agency Fees',NULL),
		(16, 'OFAC', 'Office of Foreign Asset Control'),
		(17, 'Append-DS',NULL);
END
SELECT *
FROM DecisionNet.ProductGroup

SELECT
	ProductHierarchyUpdateSet.productTransactionCode,
	ProductHierarchyUpdateSet.productHierarchyValue
	INTO #ProductHierarchyUpdateSet
FROM
	(
		VALUES
		('CU01','Assets'),
		('EVG1','Assets'),
		('EVR1','Assets'),
		
		('MAP1','People'),
		('MAP2','People'),
		
		('OFC1','OFAC'),
		('OFC2','OFAC'),
		('LCSP','OFAC'),
		('LCSS','OFAC'),
		('QCOP','OFAC'),
		('QCOS','OFAC'),
	/*Criminal type search thingies*/
		('ABAA','Criminal Records'),
		('ABAD','Criminal Records'),
		('AKAA','Criminal Records'),
		('ARAF','Criminal Records'),
		('AZAB','Criminal Records'),
		('CAAB','Criminal Records'),
		('COAA','Criminal Records'),
		('CTAB','Criminal Records'),
		('DEAA','Criminal Records'),
		('FLAB','Criminal Records'),
		('FLAF','Criminal Records'),
		('HIAA','Criminal Records'),
		('IAAA','Criminal Records'),
		('IAAB','Criminal Records'),
		('ILAB','Criminal Records'),
		('KSAA','Criminal Records'),
		('KYAB','Criminal Records'),
		('MDAA','Criminal Records'),
		('MEAA','Criminal Records'),
		('MIAB','Criminal Records'),
		('MNAC','Criminal Records'),
		('MOAB','Criminal Records'),
		('MOAF','Criminal Records'),
		('MTAB','Criminal Records'),
		('NCAA','Criminal Records'),
		('NDAB','Criminal Records'),
		('NEAA','Criminal Records'),
		('NJAA','Criminal Records'),
		('NYAA','Criminal Records'),
		('NYAE','Criminal Records'),
		('OHAA','Criminal Records'),
		('OKAB','Criminal Records'),
		('ORAC','Criminal Records'),
		('PAAA','Criminal Records'),
		('RIAA','Criminal Records'),
		('SCAA','Criminal Records'),
		('SDAA','Criminal Records'),
		('TXAA','Criminal Records'),
		('VAAA','Criminal Records'),
		('WAAA','Criminal Records'),
		('WAAB','Criminal Records'),
		('WIAB','Criminal Records'),
	/*Conviction records*/
		('AZAA','Criminal Records'),
		('CTAA','Criminal Records'),
		('FLAA','Criminal Records'),
		('GAAA','Criminal Records'),
		('IDAA','Criminal Records'),
		('ILAA','Criminal Records'),
		('INAC','Criminal Records'),
		('KYAA','Criminal Records'),
		('MIAA','Criminal Records'),
		('MNAB','Criminal Records'),
		('MOAA','Criminal Records'),
		('MSAA','Criminal Records'),
		('MTAA','Criminal Records'),
		('OKAA','Criminal Records'),
		('ORAA','Criminal Records'),
		('WIAA','Criminal Records'),

	/*Civil*/
		('ABAC','Criminal Records'),
		('AKAC','Criminal Records'),
		('AKAD','Criminal Records'),
		('ALAB','Criminal Records'),
		('ALAC','Criminal Records'),
		('ARAG','Criminal Records'),
		('ARAH','Criminal Records'),
		('AZAC','Criminal Records'),
		('AZAD','Criminal Records'),
		('CAAC','Criminal Records'),
		('CAAD','Criminal Records'),
		('COAB','Criminal Records'),
		('COAC','Criminal Records'),
		('CTAC','Criminal Records'),
		('CTAD','Criminal Records'),
		('DCAA','Criminal Records'),
		('DCAB','Criminal Records'),
		('DEAB','Criminal Records'),
		('DEAC','Criminal Records'),
		('FLAC','Criminal Records'),
		('FLAD','Criminal Records'),
		('GAAC','Criminal Records'),
		('GAAD','Criminal Records'),
		('HIAB','Criminal Records'),
		('HIAC','Criminal Records'),
		('IAAC','Criminal Records'),
		('IAAD','Criminal Records'),
		('IDAB','Criminal Records'),
		('IDAC','Criminal Records'),
		('ILAC','Criminal Records'),
		('ILAD','Criminal Records'),
		('INAD','Criminal Records'),
		('INAE','Criminal Records'),
		('KSAB','Criminal Records'),
		('KSAC','Criminal Records'),
		('KYAC','Criminal Records'),
		('KYAD','Criminal Records'),
		('LAAA','Criminal Records'),
		('LAAB','Criminal Records'),
		('MAAA','Criminal Records'),
		('MAAB','Criminal Records'),
		('MDAB','Criminal Records'),
		('MDAC','Criminal Records'),
		('MEAB','Criminal Records'),
		('MEAC','Criminal Records'),
		('MIAC','Criminal Records'),
		('MIAD','Criminal Records'),
		('MIAE','Criminal Records'),
		('MNAD','Criminal Records'),
		('MOAC','Criminal Records'),
		('MOAD','Criminal Records'),
		('MSAC','Criminal Records'),
		('MSAD','Criminal Records'),
		('MTAC','Criminal Records'),
		('MTAD','Criminal Records'),
		('NCAB','Criminal Records'),
		('NCAC','Criminal Records'),
		('NDAC','Criminal Records'),
		('NDAD','Criminal Records'),
		('NEAB','Criminal Records'),
		('NEAC','Criminal Records'),
		('NHAA','Criminal Records'),
		('NHAB','Criminal Records'),
		('NJAB','Criminal Records'),
		('NJAC','Criminal Records'),
		('NMAB','Criminal Records'),
		('NMAC','Criminal Records'),
		('NVAA','Criminal Records'),
		('NVAB','Criminal Records'),
		('NYAB','Criminal Records'),
		('NYAC','Criminal Records'),
		('OHAB','Criminal Records'),
		('OHAC','Criminal Records'),
		('OKAC','Criminal Records'),
		('ORAD','Criminal Records'),
		('ORAE','Criminal Records'),
		('PAAB','Criminal Records'),
		('PAAC','Criminal Records'),
		('RIAB','Criminal Records'),
		('RIAC','Criminal Records'),
		('SCAB','Criminal Records'),
		('SCAC','Criminal Records'),
		('SDAB','Criminal Records'),
		('SDAC','Criminal Records'),
		('TNAC','Criminal Records'),
		('TNAD','Criminal Records'),
		('TXAD','Criminal Records'),
		('TXAE','Criminal Records'),
		('UTAB','Criminal Records'),
		('UTAC','Criminal Records'),
		('VAAB','Criminal Records'),
		('VAAC','Criminal Records'),
		('VTAA','Criminal Records'),
		('VTAB','Criminal Records'),
		('WAAC','Criminal Records'),
		('WAAD','Criminal Records'),
		('WIAC','Criminal Records'),
		('WIAD','Criminal Records'),
		('WVAA','Criminal Records'),
		('WVAB','Criminal Records'),
		('WYAA','Criminal Records'),
		('WYAB','Criminal Records'),

	/*Single County Search*/
		('AKAE','Criminal Records'),
		('ALAE','Criminal Records'),
		('ARAJ','Criminal Records'),
		('AZAE','Criminal Records'),
		('CAAF','Criminal Records'),
		('COAE','Criminal Records'),
		('CTAE','Criminal Records'),
		('DCAD','Criminal Records'),
		('DEAD','Criminal Records'),
		('FLAE','Criminal Records'),
		('GAAE','Criminal Records'),
		('HIAE','Criminal Records'),
		('IAAF','Criminal Records'),
		('IDAD','Criminal Records'),
		('ILAF','Criminal Records'),
		('INAF','Criminal Records'),
		('KSAF','Criminal Records'),
		('KYAE','Criminal Records'),
		('LAAD','Criminal Records'),
		('MAAC','Criminal Records'),
		('MDAE','Criminal Records'),
		('MEAF','Criminal Records'),
		('MIAG','Criminal Records'),
		('MNAE','Criminal Records'),
		('MOAE','Criminal Records'),
		('MSAF','Criminal Records'),
		('MTAE','Criminal Records'),
		('NCAE','Criminal Records'),
		('NDAF','Criminal Records'),
		('NEAE','Criminal Records'),
		('NHAE','Criminal Records'),
		('NJAE','Criminal Records'),
		('NMAE','Criminal Records'),
		('NVAD','Criminal Records'),
		('NYAF','Criminal Records'),
		('OHAE','Criminal Records'),
		('OKAG','Criminal Records'),
		('ORAF','Criminal Records'),
		('PAAE','Criminal Records'),
		('RIAE','Criminal Records'),
		('SCAF','Criminal Records'),
		('SDAE','Criminal Records'),
		('TNAF','Criminal Records'),
		('TXAG','Criminal Records'),
		('UTAE','Criminal Records'),
		('VAAE','Criminal Records'),
		('VTAD','Criminal Records'),
		('WAAE','Criminal Records'),
		('WIAF','Criminal Records'),
		('WVAC','Criminal Records'),
		('WYAC','Criminal Records'),
	
	/*single product / super */
		('ABAB','Criminal Records'),

	/*sex offender*/
		('ABAF','Criminal Records'),

	/*Agency/PreviouslyPolice*/
		('P000','Agency Fees'),
		('P001','Agency Fees'),
		('P002','Agency Fees'),
		('P003','Agency Fees'),
		('P004','Agency Fees'),
		('P005','Agency Fees'),
		('P006','Agency Fees'),
		('P007','Agency Fees'),
		('P008','Agency Fees'),
		('P009','Agency Fees'),
		('P010','Agency Fees'),
		('P011','Agency Fees'),
		('P012','Agency Fees'),
		('P013','Agency Fees'),
		('P014','Agency Fees'),
		('P015','Agency Fees'),
		('P016','Agency Fees'),
		('P017','Agency Fees'),
		('P018','Agency Fees'),
		('P019','Agency Fees'),
		('P020','Agency Fees'),
		('P021','Agency Fees'),
		('P022','Agency Fees'),
		('P023','Agency Fees'),
		('P024','Agency Fees'),
		('P025','Agency Fees'),
		('P026','Agency Fees'),
		('P027','Agency Fees'),
		('P028','Agency Fees'),
		('P029','Agency Fees'),
		('P030','Agency Fees'),
		('P031','Agency Fees'),
		('P032','Agency Fees'),
		('P033','Agency Fees'),
		('P034','Agency Fees'),
		('P035','Agency Fees'),
		('P036','Agency Fees'),
		('P037','Agency Fees'),
		('P038','Agency Fees'),
		('P039','Agency Fees'),
		('P040','Agency Fees'),
		('P041','Agency Fees'),
		('P042','Agency Fees'),
		('P043','Agency Fees'),
		('P044','Agency Fees'),
		('P045','Agency Fees'),
		('P046','Agency Fees'),
		('P047','Agency Fees'),
		('P048','Agency Fees'),
		('P049','Agency Fees'),
		('P050','Agency Fees'),
		('P051','Agency Fees'),
		('P052','Agency Fees'),
		('P053','Agency Fees'),
		('P054','Agency Fees'),
		('P055','Agency Fees'),
		('P056','Agency Fees'),
		('P057','Agency Fees'),
		('P058','Agency Fees'),
		('P059','Agency Fees'),
		('P060','Agency Fees'),
		('P061','Agency Fees'),
		('P062','Agency Fees'),
		('P063','Agency Fees'),
		('P064','Agency Fees'),
		('P065','Agency Fees'),
		('P066','Agency Fees'),
		('P067','Agency Fees'),
		('P068','Agency Fees'),
		('P069','Agency Fees'),
		('P070','Agency Fees'),
		('P071','Agency Fees'),
		('P072','Agency Fees'),
		('P073','Agency Fees'),
		('P074','Agency Fees'),
		('P075','Agency Fees'),
		('P076','Agency Fees'),
		('P077','Agency Fees'),
		('P078','Agency Fees'),
		('P079','Agency Fees'),
		('P080','Agency Fees'),
		('P081','Agency Fees'),
		('P082','Agency Fees'),
		('P083','Agency Fees'),
		('P084','Agency Fees'),
		('P085','Agency Fees'),
		('P086','Agency Fees'),
		('P087','Agency Fees'),
		('P088','Agency Fees'),
		('P089','Agency Fees'),
		('P090','Agency Fees'),
		('P091','Agency Fees'),
		('P092','Agency Fees'),
		('P093','Agency Fees'),
		('P094','Agency Fees'),
		('P095','Agency Fees'),
		('P096','Agency Fees'),
		('P097','Agency Fees'),
		('P098','Agency Fees'),
		('P099','Agency Fees'),
		('P100','Agency Fees'),
		('P101','Agency Fees'),
		('P102','Agency Fees'),
		('P103','Agency Fees'),
		('P104','Agency Fees'),
		('P105','Agency Fees'),
		('P106','Agency Fees'),
		('P107','Agency Fees'),
		('P108','Agency Fees'),
		('P109','Agency Fees'),
		('P110','Agency Fees'),
		('P111','Agency Fees'),
		('P112','Agency Fees'),
		('P113','Agency Fees'),
		('P114','Agency Fees'),
		('P115','Agency Fees'),
		('P116','Agency Fees'),
		('P117','Agency Fees'),
		('P118','Agency Fees'),
		('P119','Agency Fees'),
		('P120','Agency Fees'),
		('P121','Agency Fees'),
		('P122','Agency Fees'),
		('P123','Agency Fees'),
		('P124','Agency Fees'),
		('P125','Agency Fees'),
		('P126','Agency Fees'),
		('P127','Agency Fees'),
		('P128','Agency Fees'),
		('P129','Agency Fees'),
		('P130','Agency Fees'),
		('P131','Agency Fees'),
		('P132','Agency Fees'),
		('P133','Agency Fees'),
		('P134','Agency Fees'),
		('P135','Agency Fees'),
		('P136','Agency Fees'),
		('P137','Agency Fees'),
		('P138','Agency Fees'),
		('P139','Agency Fees'),
		('P140','Agency Fees'),
		('P141','Agency Fees'),
		('P142','Agency Fees'),
		('P143','Agency Fees'),
		('P144','Agency Fees'),
		('P145','Agency Fees'),
		('P146','Agency Fees'),
		('P147','Agency Fees'),
		('P148','Agency Fees'),
		('P149','Agency Fees'),
		('P150','Agency Fees'),
		('P151','Agency Fees'),
		('P152','Agency Fees'),
		('P153','Agency Fees'),
		('P154','Agency Fees'),
		('P155','Agency Fees'),
		('P156','Agency Fees'),
		('P157','Agency Fees'),
		('P158','Agency Fees'),
		('P159','Agency Fees'),
		('P160','Agency Fees'),
		('P161','Agency Fees'),
		('P162','Agency Fees'),
		('P163','Agency Fees'),
		('P164','Agency Fees'),
		('P165','Agency Fees'),
		('P166','Agency Fees'),
		('P167','Agency Fees'),
		('P168','Agency Fees'),
		('P169','Agency Fees'),
		('P170','Agency Fees'),
		('P171','Agency Fees'),
		('P172','Agency Fees'),
		('P173','Agency Fees'),
		('P174','Agency Fees'),
		('P175','Agency Fees'),
		('P176','Agency Fees'),
		('P177','Agency Fees'),
		('P178','Agency Fees'),
		('P179','Agency Fees'),
		('P180','Agency Fees'),
		('P181','Agency Fees'),
		('P182','Agency Fees'),
		('P183','Agency Fees'),
		('P184','Agency Fees'),
		('P185','Agency Fees'),
		('P186','Agency Fees'),
		('P187','Agency Fees'),
		('P188','Agency Fees'),
		('P189','Agency Fees'),
		('P190','Agency Fees'),
		('P191','Agency Fees'),
		('P192','Agency Fees'),
		('P193','Agency Fees'),
		('P194','Agency Fees'),
		('P195','Agency Fees'),
		('P196','Agency Fees'),
		('P197','Agency Fees'),
		('P198','Agency Fees'),
		('P199','Agency Fees'),
		('P200','Agency Fees'),
		('P201','Agency Fees'),
		('P202','Agency Fees'),
		('P203','Agency Fees'),
		('P204','Agency Fees'),
		('P205','Agency Fees'),
		('P206','Agency Fees'),
		('P207','Agency Fees'),
		('P208','Agency Fees'),
		('P209','Agency Fees'),
		('P210','Agency Fees'),
		('P211','Agency Fees'),
		('P212','Agency Fees'),
		('P213','Agency Fees'),
		('P214','Agency Fees'),
		('P215','Agency Fees'),
		('P216','Agency Fees'),
		('P217','Agency Fees'),
		('P218','Agency Fees'),
		('P219','Agency Fees'),
		('P220','Agency Fees'),
		('P221','Agency Fees'),
		('P222','Agency Fees'),
		('P223','Agency Fees'),
		('P224','Agency Fees'),
		('P225','Agency Fees'),
		('P226','Agency Fees'),
		('P227','Agency Fees'),
		('P228','Agency Fees'),
		('P229','Agency Fees'),
		('P230','Agency Fees'),
		('P231','Agency Fees'),
		('P232','Agency Fees'),
		('P233','Agency Fees'),
		('P234','Agency Fees'),
		('P235','Agency Fees'),
		('P236','Agency Fees'),
		('P237','Agency Fees'),
		('P238','Agency Fees'),
		('P239','Agency Fees'),
		('P240','Agency Fees'),
		('P241','Agency Fees'),
		('P242','Agency Fees'),
		('P243','Agency Fees'),
		('P244','Agency Fees'),
		('P245','Agency Fees'),
		('P246','Agency Fees'),
		('P247','Agency Fees'),
		('P248','Agency Fees'),
		('P249','Agency Fees'),
		('P250','Agency Fees'),
		('P251','Agency Fees'),
		('P252','Agency Fees'),
		('P253','Agency Fees'),
		('P254','Agency Fees'),
		('P255','Agency Fees'),
		('P256','Agency Fees'),
		('P257','Agency Fees'),
		('P258','Agency Fees'),
		('P259','Agency Fees'),
		('P260','Agency Fees'),
		('P261','Agency Fees'),
		('P262','Agency Fees'),
		('P263','Agency Fees'),
		('P264','Agency Fees'),
		('P265','Agency Fees'),
		('P266','Agency Fees'),
		('P267','Agency Fees'),
		('P268','Agency Fees'),
		('P269','Agency Fees'),
		('P270','Agency Fees'),
		('P271','Agency Fees'),
		('P272','Agency Fees'),
		('P273','Agency Fees'),
		('P274','Agency Fees'),
		('P275','Agency Fees'),
		('P276','Agency Fees'),
		('P277','Agency Fees'),
		('P278','Agency Fees'),
		('P279','Agency Fees'),
		('P280','Agency Fees'),
		('P281','Agency Fees'),
		('P282','Agency Fees'),
		('P283','Agency Fees'),
		('P284','Agency Fees'),
		('P285','Agency Fees'),
		('P286','Agency Fees'),
		('P287','Agency Fees'),
		('P288','Agency Fees'),
		('P289','Agency Fees'),
		('P290','Agency Fees'),
		('P291','Agency Fees'),
		('P292','Agency Fees'),
		('P293','Agency Fees'),
		('P294','Agency Fees'),
		('P295','Agency Fees'),
		('P296','Agency Fees'),
		('P297','Agency Fees'),
		('P298','Agency Fees'),
		('P299','Agency Fees'),
		('P300','Agency Fees'),
		('P301','Agency Fees'),
		('P302','Agency Fees'),
		('P303','Agency Fees'),
		('P304','Agency Fees'),
		('P305','Agency Fees'),
		('P306','Agency Fees'),
		('P307','Agency Fees'),
		('P308','Agency Fees'),
		('P309','Agency Fees'),
		('P310','Agency Fees'),
		('P311','Agency Fees'),
		('P312','Agency Fees'),
		('P313','Agency Fees'),
		('P314','Agency Fees'),
		('P315','Agency Fees'),
		('P316','Agency Fees'),
		('P317','Agency Fees'),
		('P318','Agency Fees'),
		('P319','Agency Fees'),
		('P320','Agency Fees'),
		('P321','Agency Fees'),
		('P322','Agency Fees'),
		('P323','Agency Fees'),
		('P324','Agency Fees'),
		('P325','Agency Fees'),
		('P326','Agency Fees'),
		('P327','Agency Fees'),
		('P328','Agency Fees'),
		('P329','Agency Fees'),
		('P330','Agency Fees'),
		('P331','Agency Fees'),
		('P332','Agency Fees'),
		('P333','Agency Fees'),
		('P334','Agency Fees'),
		('P335','Agency Fees'),
		('P336','Agency Fees'),
		('P337','Agency Fees'),
		('P338','Agency Fees'),
		('P339','Agency Fees'),
		('P340','Agency Fees'),
		('P341','Agency Fees'),
		('P342','Agency Fees'),
		('P343','Agency Fees'),
		('P344','Agency Fees'),
		('P345','Agency Fees'),
		('P346','Agency Fees'),
		('P347','Agency Fees'),
		('P348','Agency Fees'),
		('P349','Agency Fees'),
		('P350','Agency Fees'),
		('P351','Agency Fees'),
		('P352','Agency Fees'),
		('P353','Agency Fees'),
		('P354','Agency Fees'),
		('P355','Agency Fees'),
		('P356','Agency Fees'),
		('P357','Agency Fees'),
		('P358','Agency Fees'),
		('P359','Agency Fees'),
		('P360','Agency Fees'),
		('P361','Agency Fees'),
		('P362','Agency Fees'),
		('P363','Agency Fees'),
		('P364','Agency Fees'),
		('P365','Agency Fees'),
		('P366','Agency Fees'),
		('P367','Agency Fees'),
		('P368','Agency Fees'),
		('P369','Agency Fees'),
		('P370','Agency Fees'),
		('P371','Agency Fees'),
		('P372','Agency Fees'),
		('P373','Agency Fees'),
		('P374','Agency Fees'),
		('P375','Agency Fees'),
		('P376','Agency Fees'),
		('P377','Agency Fees'),
		('P378','Agency Fees'),
		('P379','Agency Fees'),
		('P380','Agency Fees'),
		('P381','Agency Fees'),
		('P382','Agency Fees'),
		('P383','Agency Fees'),
		('P384','Agency Fees'),
		('P385','Agency Fees'),
		('P386','Agency Fees'),
		('P387','Agency Fees'),
		('P388','Agency Fees'),
		('P389','Agency Fees'),
		('P390','Agency Fees'),
		('P391','Agency Fees'),
		('P392','Agency Fees'),
		('P393','Agency Fees'),
		('P394','Agency Fees'),
		('P395','Agency Fees'),
		('P396','Agency Fees'),
		('P397','Agency Fees'),
		('P398','Agency Fees'),
		('P399','Agency Fees'),
		('P400','Agency Fees'),
		('P401','Agency Fees'),
		('P402','Agency Fees'),
		('P403','Agency Fees'),
		('P404','Agency Fees'),
		('P405','Agency Fees'),
		('P406','Agency Fees'),
		('P407','Agency Fees'),
		('P408','Agency Fees'),
		('P409','Agency Fees'),
		('P410','Agency Fees'),
		('P411','Agency Fees'),
		('P412','Agency Fees'),
		('P413','Agency Fees'),
		('P414','Agency Fees'),
		('P415','Agency Fees'),
		('P416','Agency Fees'),
		('P417','Agency Fees'),
		('P418','Agency Fees'),
		('P419','Agency Fees'),
		('P420','Agency Fees'),
		('P421','Agency Fees'),
		('P422','Agency Fees'),
		('P423','Agency Fees'),
		('P424','Agency Fees'),
		('P425','Agency Fees'),
		('P426','Agency Fees'),
		('P427','Agency Fees'),
		('P428','Agency Fees'),
		('P429','Agency Fees'),
		('P430','Agency Fees'),
		('P431','Agency Fees'),
		('P432','Agency Fees'),
		('P433','Agency Fees'),
		('P434','Agency Fees'),
		('P435','Agency Fees'),
		('P436','Agency Fees'),
		('P437','Agency Fees'),
		('P438','Agency Fees'),
		('P439','Agency Fees'),
		('P440','Agency Fees'),
		('P441','Agency Fees'),
		('P442','Agency Fees'),
		('P443','Agency Fees'),
		('P444','Agency Fees'),
		('P445','Agency Fees'),
		('P446','Agency Fees'),
		('P447','Agency Fees'),
		('P448','Agency Fees'),
		('P449','Agency Fees'),
		('P450','Agency Fees'),
		('P451','Agency Fees'),
		('P452','Agency Fees'),
		('P453','Agency Fees'),
		('P454','Agency Fees'),
		('P455','Agency Fees'),
		('P456','Agency Fees'),
		('P457','Agency Fees'),
		('P458','Agency Fees'),
		('P459','Agency Fees'),
		('P460','Agency Fees'),
		('P461','Agency Fees'),
		('P462','Agency Fees'),
		('P463','Agency Fees'),
		('P464','Agency Fees'),
		('P465','Agency Fees'),
		('P466','Agency Fees'),
		('P467','Agency Fees'),
		('P468','Agency Fees'),
		('P469','Agency Fees'),
		('P470','Agency Fees'),
		('P471','Agency Fees'),
		('P472','Agency Fees'),
		('P473','Agency Fees'),
		('P474','Agency Fees'),
		('P475','Agency Fees'),
		('P476','Agency Fees'),
		('P477','Agency Fees'),
		('P478','Agency Fees'),
		('P479','Agency Fees'),
		('P480','Agency Fees'),
		('P481','Agency Fees'),
		('P482','Agency Fees'),
		('P483','Agency Fees'),
		('P484','Agency Fees'),
		('P485','Agency Fees'),
		('P486','Agency Fees'),
		('P487','Agency Fees'),
		('P488','Agency Fees'),
		('P489','Agency Fees'),
		('P490','Agency Fees'),
		('P491','Agency Fees'),
		('P492','Agency Fees'),
		('P493','Agency Fees'),
		('P494','Agency Fees'),
		('P495','Agency Fees'),
		('P496','Agency Fees'),
		('P497','Agency Fees'),
		('P498','Agency Fees'),
		('P499','Agency Fees'),
		('P500','Agency Fees'),
		('P501','Agency Fees'),
		('P502','Agency Fees'),
		('P503','Agency Fees'),
		('P504','Agency Fees'),
		('P505','Agency Fees'),
		('P506','Agency Fees'),
		('P507','Agency Fees'),
		('P508','Agency Fees'),
		('P509','Agency Fees'),
		('P510','Agency Fees'),
		('P511','Agency Fees'),
		('P512','Agency Fees'),
		('P513','Agency Fees'),
		('P514','Agency Fees'),
		('P515','Agency Fees'),
		('P516','Agency Fees'),
		('P517','Agency Fees'),
		('P518','Agency Fees'),
		('P519','Agency Fees'),
		('P520','Agency Fees'),
		('P521','Agency Fees'),
		('P522','Agency Fees'),
		('P523','Agency Fees'),
		('P524','Agency Fees'),
		('P525','Agency Fees'),
		('P526','Agency Fees'),
		('P527','Agency Fees'),
		('P528','Agency Fees'),
		('P529','Agency Fees'),
		('P530','Agency Fees'),
		('P531','Agency Fees'),
		('P532','Agency Fees'),
		('P533','Agency Fees'),
		('P534','Agency Fees'),
		('P535','Agency Fees'),
		('P536','Agency Fees'),
		('P537','Agency Fees'),
		('P538','Agency Fees'),
		('P539','Agency Fees'),
		('P540','Agency Fees'),
		('P541','Agency Fees'),
		('P542','Agency Fees'),
		('P543','Agency Fees'),
		('P544','Agency Fees'),
		('P545','Agency Fees'),
		('P546','Agency Fees'),
		('P547','Agency Fees'),
		('P548','Agency Fees'),
		('P549','Agency Fees'),
		('P550','Agency Fees'),
		('P551','Agency Fees'),
		('P552','Agency Fees'),
		('P553','Agency Fees'),
		('P554','Agency Fees'),
		('P555','Agency Fees'),
		('P556','Agency Fees'),
		('P557','Agency Fees'),
		('P558','Agency Fees'),
		('P559','Agency Fees'),
		('P560','Agency Fees'),
		('P561','Agency Fees'),
		('P562','Agency Fees'),
		('P563','Agency Fees'),
		('P564','Agency Fees'),
		('P565','Agency Fees'),
		('P566','Agency Fees'),
		('P567','Agency Fees'),
		('P568','Agency Fees'),
		('P569','Agency Fees'),
		('P570','Agency Fees'),
		('P571','Agency Fees'),
		('P572','Agency Fees'),
		('P573','Agency Fees'),
		('P574','Agency Fees'),
		('P575','Agency Fees'),
		('P576','Agency Fees'),
		('P577','Agency Fees'),
		('P578','Agency Fees'),
		('P579','Agency Fees'),
		('P580','Agency Fees'),
		('P581','Agency Fees'),
		('P582','Agency Fees'),
		('P583','Agency Fees'),
		('P584','Agency Fees'),
		('P585','Agency Fees'),
		('P586','Agency Fees'),
		('P587','Agency Fees'),
		('P588','Agency Fees'),
		('P589','Agency Fees'),
		('P590','Agency Fees'),
		('P591','Agency Fees'),
		('P592','Agency Fees'),
		('P593','Agency Fees'),
		('P594','Agency Fees'),
		('P595','Agency Fees'),
		('P596','Agency Fees'),
		('P597','Agency Fees'),
		('P598','Agency Fees'),
		('P599','Agency Fees'),
		('P600','Agency Fees'),
		('P601','Agency Fees'),
		('P602','Agency Fees'),
		('P603','Agency Fees'),
		('P604','Agency Fees'),
		('P605','Agency Fees'),
		('P606','Agency Fees'),
		('P607','Agency Fees'),
		('P608','Agency Fees'),
		('P609','Agency Fees'),
		('P610','Agency Fees'),
		('P611','Agency Fees'),
		('P612','Agency Fees'),
		('P613','Agency Fees'),
		('P614','Agency Fees'),
		('P615','Agency Fees'),
		('P616','Agency Fees'),
		('P617','Agency Fees'),
		('P618','Agency Fees'),
		('P619','Agency Fees'),
		('P620','Agency Fees'),
		('P621','Agency Fees'),
		('P622','Agency Fees'),
		('P623','Agency Fees'),
		('P624','Agency Fees'),
		('P625','Agency Fees'),
		('P626','Agency Fees'),
		('P627','Agency Fees'),
		('P628','Agency Fees'),
		('P629','Agency Fees'),
		('P630','Agency Fees'),
		('P631','Agency Fees'),
		('P632','Agency Fees'),
		('P633','Agency Fees'),
		('P634','Agency Fees'),
		('P635','Agency Fees'),
		('P636','Agency Fees'),
		('P637','Agency Fees'),
		('P638','Agency Fees'),
		('P639','Agency Fees'),
		('P640','Agency Fees'),
		('P641','Agency Fees'),
		('P642','Agency Fees'),
		('P643','Agency Fees'),
		('P644','Agency Fees'),
		('P645','Agency Fees'),
		('P646','Agency Fees'),
		('P647','Agency Fees'),
		('P648','Agency Fees'),
		('P649','Agency Fees'),
		('P650','Agency Fees'),
		('P651','Agency Fees'),
		('P652','Agency Fees'),
		('P653','Agency Fees'),
		('P654','Agency Fees'),
		('P655','Agency Fees'),
		('P656','Agency Fees'),
		('P657','Agency Fees'),
		('P658','Agency Fees'),
		('P659','Agency Fees'),
		('P660','Agency Fees'),
		('P661','Agency Fees'),
		('P662','Agency Fees'),
		('P663','Agency Fees'),
		('P664','Agency Fees'),
		('P665','Agency Fees'),
		('P666','Agency Fees'),
		('P667','Agency Fees'),
		('P668','Agency Fees'),
		('P669','Agency Fees'),
		('P670','Agency Fees'),
		('P671','Agency Fees'),
		('P672','Agency Fees'),
		('P673','Agency Fees'),
		('P674','Agency Fees'),
		('P675','Agency Fees'),
		('P676','Agency Fees'),
		('P677','Agency Fees'),
		('P678','Agency Fees'),
		('P679','Agency Fees'),
		('P680','Agency Fees'),
		('P681','Agency Fees'),
		('P682','Agency Fees'),
		('P683','Agency Fees'),
		('P684','Agency Fees'),
		('P685','Agency Fees'),
		('P686','Agency Fees'),
		('P687','Agency Fees'),
		('P688','Agency Fees'),
		('P689','Agency Fees'),
		('P690','Agency Fees'),
		('P691','Agency Fees'),
		('P692','Agency Fees'),
		('P693','Agency Fees'),
		('P694','Agency Fees'),
		('P695','Agency Fees'),
		('P696','Agency Fees'),
		('P697','Agency Fees'),
		('P698','Agency Fees'),
		('P699','Agency Fees'),
		('P700','Agency Fees'),
		('P701','Agency Fees'),
		('P702','Agency Fees'),
		('P703','Agency Fees'),
		('P704','Agency Fees'),
		('P705','Agency Fees'),
		('P706','Agency Fees'),
		('P707','Agency Fees'),
		('P708','Agency Fees'),
		('P709','Agency Fees'),
		('P710','Agency Fees'),
		('P711','Agency Fees'),
		('P712','Agency Fees'),
		('P713','Agency Fees'),
		('P714','Agency Fees'),
		('P715','Agency Fees'),
		('P716','Agency Fees'),
		('P717','Agency Fees'),
		('P718','Agency Fees'),
		('P719','Agency Fees'),
		('P720','Agency Fees'),
		('P721','Agency Fees'),
		('P722','Agency Fees'),
		('P723','Agency Fees'),
		('P724','Agency Fees'),
		('P725','Agency Fees'),
		('P726','Agency Fees'),
		('P727','Agency Fees'),
		('P728','Agency Fees'),
		('P729','Agency Fees'),
		('P730','Agency Fees'),
		('P731','Agency Fees'),
		('P732','Agency Fees'),
		('P733','Agency Fees'),
		('P734','Agency Fees'),
		('P735','Agency Fees'),
		('P736','Agency Fees'),
		('P737','Agency Fees'),
		('P738','Agency Fees'),
		('P739','Agency Fees'),
		('P740','Agency Fees'),
		('P741','Agency Fees'),
		('P742','Agency Fees'),
		('P743','Agency Fees'),
		('P744','Agency Fees'),
		('P745','Agency Fees'),
		('P746','Agency Fees'),
		('P747','Agency Fees'),
		('P748','Agency Fees'),
		('P749','Agency Fees'),
		('P750','Agency Fees'),
		('P751','Agency Fees'),
		('P752','Agency Fees'),
		('P753','Agency Fees'),
		('P754','Agency Fees'),
		('P755','Agency Fees'),
		('P756','Agency Fees'),
		('P757','Agency Fees'),
		('P758','Agency Fees'),
		('P759','Agency Fees'),
		('P760','Agency Fees'),
		('P761','Agency Fees'),
		('P762','Agency Fees'),
		('P763','Agency Fees'),
		('P764','Agency Fees'),
		('P765','Agency Fees'),
		('P766','Agency Fees'),
		('P767','Agency Fees'),
		('P768','Agency Fees'),
		('P769','Agency Fees'),
		('P770','Agency Fees'),
		('P771','Agency Fees'),
		('P772','Agency Fees'),
		('P773','Agency Fees'),
		('P774','Agency Fees'),
		('P775','Agency Fees'),
		('P776','Agency Fees'),
		('P777','Agency Fees'),
		('P778','Agency Fees'),
		('P779','Agency Fees'),
		('P780','Agency Fees'),
		('P781','Agency Fees'),
		('P782','Agency Fees'),
		('P783','Agency Fees'),
		('P784','Agency Fees'),
		('P785','Agency Fees'),
		('P786','Agency Fees'),
		('P787','Agency Fees'),
		('P788','Agency Fees'),
		('P789','Agency Fees'),
		('P790','Agency Fees'),
		('P791','Agency Fees'),
		('P792','Agency Fees'),
		('P793','Agency Fees'),
		('P794','Agency Fees'),
		('P795','Agency Fees'),
		('P796','Agency Fees'),
		('P797','Agency Fees'),
		('P798','Agency Fees'),
		('P799','Agency Fees'),
		('P800','Agency Fees'),
		('P801','Agency Fees'),
		('P802','Agency Fees'),
		('P803','Agency Fees'),
		('P804','Agency Fees'),
		('P805','Agency Fees'),
		('P806','Agency Fees'),
		('P807','Agency Fees'),
		('P808','Agency Fees'),
		('P809','Agency Fees'),
		('P810','Agency Fees'),
		('P811','Agency Fees'),
		('P812','Agency Fees'),
		('P813','Agency Fees'),
		('P814','Agency Fees'),
		('P815','Agency Fees'),
		('P816','Agency Fees'),
		('P817','Agency Fees'),
		('P818','Agency Fees'),
		('P819','Agency Fees'),
		('P820','Agency Fees'),
		('P821','Agency Fees'),
		('P822','Agency Fees'),
		('P823','Agency Fees'),
		('P824','Agency Fees'),
		('P825','Agency Fees'),
		('P826','Agency Fees'),
		('P827','Agency Fees'),
		('P828','Agency Fees'),
		('P829','Agency Fees'),
		('P830','Agency Fees'),
		('P831','Agency Fees'),
		('P832','Agency Fees'),
		('P833','Agency Fees'),
		('P834','Agency Fees'),
		('P835','Agency Fees'),
		('P836','Agency Fees'),
		('P837','Agency Fees'),
		('P838','Agency Fees'),
		('P839','Agency Fees'),
		('P840','Agency Fees'),
		('P841','Agency Fees'),
		('P842','Agency Fees'),
		('P843','Agency Fees'),
		('P844','Agency Fees'),
		('P845','Agency Fees'),
		('P846','Agency Fees'),
		('P847','Agency Fees'),
		('P848','Agency Fees'),
		('P849','Agency Fees'),
		('P850','Agency Fees'),
		('P851','Agency Fees'),
		('P852','Agency Fees'),
		('P853','Agency Fees'),
		('P854','Agency Fees'),
		('P855','Agency Fees'),
		('P856','Agency Fees'),
		('P857','Agency Fees'),
		('P858','Agency Fees'),
		('P859','Agency Fees'),
		('P860','Agency Fees'),
		('P861','Agency Fees'),
		('P862','Agency Fees'),
		('P863','Agency Fees'),
		('P864','Agency Fees'),
		('P865','Agency Fees'),
		('P866','Agency Fees'),
		('P867','Agency Fees'),
		('P868','Agency Fees'),
		('P869','Agency Fees'),
		('P870','Agency Fees'),
		('P871','Agency Fees'),
		('P872','Agency Fees'),
		('P873','Agency Fees'),
		('P874','Agency Fees'),
		('P875','Agency Fees'),
		('P876','Agency Fees'),
		('P877','Agency Fees'),
		('P878','Agency Fees'),
		('P879','Agency Fees'),
		('P880','Agency Fees'),
		('P881','Agency Fees'),
		('P882','Agency Fees'),
		('P883','Agency Fees'),
		('P884','Agency Fees'),
		('P885','Agency Fees'),
		('P886','Agency Fees'),
		('P887','Agency Fees'),
		('P888','Agency Fees'),
		('P889','Agency Fees'),
		('P890','Agency Fees'),
		('P891','Agency Fees'),
		('P892','Agency Fees'),
		('P893','Agency Fees'),
		('P894','Agency Fees'),
		('P895','Agency Fees'),
		('P896','Agency Fees'),
		('P897','Agency Fees'),
		('P898','Agency Fees'),
		('P899','Agency Fees'),
		('P900','Agency Fees'),
		('P901','Agency Fees'),
		('P902','Agency Fees'),
		('P903','Agency Fees'),
		('P904','Agency Fees'),
		('P905','Agency Fees'),
		('P906','Agency Fees'),
		('P907','Agency Fees'),
		('P908','Agency Fees'),
		('P909','Agency Fees'),
		('P910','Agency Fees'),
		('P911','Agency Fees'),
		('P912','Agency Fees'),
		('P913','Agency Fees'),
		('P914','Agency Fees'),
		('P915','Agency Fees'),
		('P916','Agency Fees'),
		('P917','Agency Fees'),
		('P918','Agency Fees'),
		('P919','Agency Fees'),
		('P920','Agency Fees'),
		('P921','Agency Fees'),
		('P922','Agency Fees'),
		('P923','Agency Fees'),
		('P924','Agency Fees'),
		('P925','Agency Fees'),
		('P926','Agency Fees'),
		('P927','Agency Fees'),
		('P928','Agency Fees'),
		('P929','Agency Fees'),
		('P930','Agency Fees'),
		('P931','Agency Fees'),
		('P932','Agency Fees'),
		('P933','Agency Fees'),
		('P934','Agency Fees'),
		('P935','Agency Fees'),
		('P936','Agency Fees'),
		('P937','Agency Fees'),
		('P938','Agency Fees'),
		('P939','Agency Fees'),
		('P940','Agency Fees'),
		('P941','Agency Fees'),
		('P942','Agency Fees'),
		('P943','Agency Fees'),
		('P944','Agency Fees'),
		('P945','Agency Fees'),
		('P946','Agency Fees'),
		('P947','Agency Fees'),
		('P948','Agency Fees'),
		('P949','Agency Fees'),
		('P950','Agency Fees'),
		('P951','Agency Fees'),
		('P952','Agency Fees'),
		('P953','Agency Fees'),
		('P954','Agency Fees'),
		('P955','Agency Fees'),
		('P956','Agency Fees'),
		('P957','Agency Fees'),
		('P958','Agency Fees'),
		('P959','Agency Fees'),
		('P960','Agency Fees'),
		('P961','Agency Fees'),
		('P962','Agency Fees'),
		('P963','Agency Fees'),
		('P964','Agency Fees'),
		('P965','Agency Fees'),
		('P966','Agency Fees'),
		('P967','Agency Fees'),
		('P968','Agency Fees'),
		('P969','Agency Fees'),
		('P970','Agency Fees'),
		('P971','Agency Fees'),
		('P972','Agency Fees'),
		('P973','Agency Fees'),
		('P974','Agency Fees'),
		('P975','Agency Fees'),
		('P976','Agency Fees'),
		('P977','Agency Fees'),
		('P978','Agency Fees'),
		('P979','Agency Fees'),
		('P980','Agency Fees'),
		('P981','Agency Fees'),
		('P982','Agency Fees'),
		('P983','Agency Fees'),
		('P984','Agency Fees'),
		('P985','Agency Fees'),
		('P986','Agency Fees'),
		('P987','Agency Fees'),
		('P988','Agency Fees'),
		('P989','Agency Fees'),
		('P990','Agency Fees'),
		('P991','Agency Fees'),
		('P992','Agency Fees'),
		('P993','Agency Fees'),
		('P994','Agency Fees'),
		('P995','Agency Fees'),
		('P996','Agency Fees'),
		('P997','Agency Fees'),
		('P998','Agency Fees'),
		('P999','Agency Fees'),
		('S001','Agency Fees'),
		('S002','Agency Fees'),
		('S003','Agency Fees'),
		('S004','Agency Fees'),
		('S005','Agency Fees'),
		('S006','Agency Fees'),
		('S007','Agency Fees'),
		('S008','Agency Fees'),
		('S009','Agency Fees'),
		('S010','Agency Fees'),
		('S011','Agency Fees'),
		('S012','Agency Fees'),
		('S013','Agency Fees'),
		('S014','Agency Fees'),
		('S015','Agency Fees'),
		('S016','Agency Fees'),
		('S017','Agency Fees'),
		('S018','Agency Fees'),
		('S019','Agency Fees'),
		('S020','Agency Fees'),
		('S021','Agency Fees'),
		('S022','Agency Fees'),
		('S023','Agency Fees'),
		('S024','Agency Fees'),
		('S025','Agency Fees'),
		('S026','Agency Fees'),
		('S027','Agency Fees'),
		('S028','Agency Fees'),
		('S029','Agency Fees'),
		('S030','Agency Fees'),
		('S031','Agency Fees'),
		('S032','Agency Fees'),
		('S033','Agency Fees'),
		('S034','Agency Fees'),
		('S035','Agency Fees'),
		('S036','Agency Fees'),
		('S037','Agency Fees'),
		('S038','Agency Fees'),
		('S039','Agency Fees'),
		('S040','Agency Fees'),
		('S041','Agency Fees'),
		('S042','Agency Fees'),
		('S043','Agency Fees'),
		('S044','Agency Fees'),
		('S045','Agency Fees'),
		('S046','Agency Fees'),
		('S047','Agency Fees'),
		('S048','Agency Fees'),
		('S049','Agency Fees'),
		('S050','Agency Fees'),
		('S051','Agency Fees'),
		('S052','Agency Fees'),
		('S053','Agency Fees'),
		('S054','Agency Fees'),
		('S055','Agency Fees'),
		('S056','Agency Fees'),
		('S057','Agency Fees'),
		('S058','Agency Fees'),
		('S059','Agency Fees'),
		('S060','Agency Fees'),
		('S061','Agency Fees'),
		('S062','Agency Fees'),
		('S063','Agency Fees'),
		('S064','Agency Fees'),
		('S065','Agency Fees'),
		('S066','Agency Fees'),
		('S067','Agency Fees'),
		('S068','Agency Fees'),
		('S069','Agency Fees'),
		('S070','Agency Fees'),
		('S071','Agency Fees'),
		('S072','Agency Fees'),
		('S073','Agency Fees'),
		('S074','Agency Fees'),
		('S075','Agency Fees'),
		('S076','Agency Fees'),
		('S077','Agency Fees'),
		('S078','Agency Fees'),
		('S079','Agency Fees'),
		('S080','Agency Fees'),
		('S081','Agency Fees'),
		('S082','Agency Fees'),
		('S083','Agency Fees'),
		('S084','Agency Fees'),
		('S085','Agency Fees'),
		('S086','Agency Fees'),
		('S087','Agency Fees'),
		('S088','Agency Fees'),
		('S089','Agency Fees'),
		('S090','Agency Fees'),
		('S091','Agency Fees'),
		('S092','Agency Fees'),
		('S093','Agency Fees'),
		('S094','Agency Fees'),
		('S095','Agency Fees'),
		('S096','Agency Fees'),
		('S099','Agency Fees'),
		('S100','Agency Fees'),
		('S101','Agency Fees'),
		('S102','Agency Fees'),
		('S103','Agency Fees'),
		('S104','Agency Fees'),
		('S105','Agency Fees'),
		('S106','Agency Fees'),
		('S107','Agency Fees'),
		('S108','Agency Fees'),
		('S109','Agency Fees'),
		('S110','Agency Fees'),
		('S111','Agency Fees'),
		('S112','Agency Fees'),
		('S113','Agency Fees'),
		('S114','Agency Fees'),
		('S115','Agency Fees'),
		('S116','Agency Fees'),
		('S117','Agency Fees'),
		('S118','Agency Fees'),
		('S119','Agency Fees'),
		('S120','Agency Fees'),
		('S121','Agency Fees'),
		('S122','Agency Fees'),
		('S123','Agency Fees'),
		('S124','Agency Fees'),
		('S125','Agency Fees'),
		('S127','Agency Fees'),
		('S128','Agency Fees'),
		('S129','Agency Fees'),
		('S130','Agency Fees'),
		('S131','Agency Fees'),
		('S132','Agency Fees'),
		('S133','Agency Fees'),
		('S134','Agency Fees'),
		('S135','Agency Fees'),
		('S136','Agency Fees'),
		('S137','Agency Fees'),
		('S138','Agency Fees'),
		('S139','Agency Fees'),
		('S140','Agency Fees'),
		('S141','Agency Fees'),
		('S142','Agency Fees'),
		('S143','Agency Fees'),
		('S144','Agency Fees'),
		('S145','Agency Fees'),
		('S146','Agency Fees'),
		('S147','Agency Fees'),
		('S148','Agency Fees'),
		('S149','Agency Fees'),
		('S150','Agency Fees'),
		('S151','Agency Fees'),
		('S152','Agency Fees'),
		('S153','Agency Fees'),
		('S154','Agency Fees'),
		('S155','Agency Fees'),
		('S156','Agency Fees'),
		('S157','Agency Fees'),
		('S159','Agency Fees'),
		('S160','Agency Fees'),
		('S161','Agency Fees'),
		('S162','Agency Fees'),
		('S163','Agency Fees'),
		('S164','Agency Fees'),
		('S165','Agency Fees'),
		('S167','Agency Fees'),
		('S168','Agency Fees'),
		('S169','Agency Fees'),
		('S170','Agency Fees'),
		('S171','Agency Fees'),
		('S172','Agency Fees'),
		('S173','Agency Fees'),
		('S174','Agency Fees'),
		('S175','Agency Fees'),
		('S176','Agency Fees'),
		('S177','Agency Fees'),
		('S180','Agency Fees'),
		('S181','Agency Fees'),
		('S182','Agency Fees'),
		('S183','Agency Fees'),
		('S184','Agency Fees'),
		('S185','Agency Fees'),
		('S189','Agency Fees'),
		('S190','Agency Fees'),
		('S191','Agency Fees'),
		('S192','Agency Fees'),
		('S194','Agency Fees'),
		('S195','Agency Fees'),
		('S197','Agency Fees'),
		('S199','Agency Fees'),
		('S200','Agency Fees'),
		('S201','Agency Fees'),
		('S204','Agency Fees'),
		('S205','Agency Fees'),
		('S206','Agency Fees'),
		('S207','Agency Fees'),
		('S209','Agency Fees'),
		('S210','Agency Fees'),
		('S211','Agency Fees'),
		('S212','Agency Fees'),
		('S213','Agency Fees'),
		('S215','Agency Fees'),
		('S217','Agency Fees'),
		('S219','Agency Fees'),
		('S220','Agency Fees'),
		('S221','Agency Fees'),
		('S222','Agency Fees'),
		('S223','Agency Fees'),
		('S224','Agency Fees'),
		('S225','Agency Fees'),
		('S227','Agency Fees'),
		('S229','Agency Fees'),
		('S230','Agency Fees'),
		('S234','Agency Fees'),
		('S235','Agency Fees'),
		('S237','Agency Fees'),
		('S239','Agency Fees'),
		('S240','Agency Fees'),
		('S241','Agency Fees'),
		('S243','Agency Fees'),
		('S245','Agency Fees'),
		('S247','Agency Fees'),
		('S250','Agency Fees'),
		('S251','Agency Fees'),
		('S253','Agency Fees'),
		('S254','Agency Fees'),
		('S255','Agency Fees'),
		('S257','Agency Fees'),
		('S260','Agency Fees'),
		('S261','Agency Fees'),
		('S263','Agency Fees'),
		('S264','Agency Fees'),
		('S265','Agency Fees'),
		('S266','Agency Fees'),
		('S270','Agency Fees'),
		('S271','Agency Fees'),
		('S272','Agency Fees'),
		('S274','Agency Fees'),
		('S275','Agency Fees'),
		('S277','Agency Fees'),
		('S280','Agency Fees'),
		('S282','Agency Fees'),
		('S285','Agency Fees'),
		('S286','Agency Fees'),
		('S290','Agency Fees'),
		('S295','Agency Fees'),
		('S300','Agency Fees'),
		('S302','Agency Fees'),
		('S303','Agency Fees'),
		('S304','Agency Fees'),
		('S305','Agency Fees'),
		('S309','Agency Fees'),
		('S310','Agency Fees'),
		('S311','Agency Fees'),
		('S313','Agency Fees'),
		('S315','Agency Fees'),
		('S316','Agency Fees'),
		('S317','Agency Fees'),
		('S319','Agency Fees'),
		('S320','Agency Fees'),
		('S321','Agency Fees'),
		('S323','Agency Fees'),
		('S325','Agency Fees'),
		('S327','Agency Fees'),
		('S329','Agency Fees'),
		('S330','Agency Fees'),
		('S331','Agency Fees'),
		('S333','Agency Fees'),
		('S335','Agency Fees'),
		('S337','Agency Fees'),
		('S339','Agency Fees'),
		('S340','Agency Fees'),
		('S341','Agency Fees'),
		('S342','Agency Fees'),
		('S343','Agency Fees'),
		('S345','Agency Fees'),
		('S347','Agency Fees'),
		('S348','Agency Fees'),
		('S349','Agency Fees'),
		('S350','Agency Fees'),
		('S351','Agency Fees'),
		('S353','Agency Fees'),
		('S355','Agency Fees'),
		('S357','Agency Fees'),
		('S360','Agency Fees'),
		('S361','Agency Fees'),
		('S362','Agency Fees'),
		('S365','Agency Fees'),
		('S370','Agency Fees'),
		('S371','Agency Fees'),
		('S375','Agency Fees'),
		('S380','Agency Fees'),
		('S381','Agency Fees'),
		('S382','Agency Fees'),
		('S383','Agency Fees'),
		('S384','Agency Fees'),
		('S385','Agency Fees'),
		('S390','Agency Fees'),
		('S395','Agency Fees'),
		('S396','Agency Fees'),
		('S400','Agency Fees'),
		('S404','Agency Fees'),
		('S405','Agency Fees'),
		('S409','Agency Fees'),
		('S410','Agency Fees'),
		('S411','Agency Fees'),
		('S412','Agency Fees'),
		('S415','Agency Fees'),
		('S420','Agency Fees'),
		('S423','Agency Fees'),
		('S424','Agency Fees'),
		('S425','Agency Fees'),
		('S430','Agency Fees'),
		('S436','Agency Fees'),
		('S440','Agency Fees'),
		('S441','Agency Fees'),
		('S442','Agency Fees'),
		('S445','Agency Fees'),
		('S447','Agency Fees'),
		('S450','Agency Fees'),
		('S452','Agency Fees'),
		('S455','Agency Fees'),
		('S460','Agency Fees'),
		('S462','Agency Fees'),
		('S465','Agency Fees'),
		('S466','Agency Fees'),
		('S469','Agency Fees'),
		('S470','Agency Fees'),
		('S471','Agency Fees'),
		('S475','Agency Fees'),
		('S480','Agency Fees'),
		('S482','Agency Fees'),
		('S483','Agency Fees'),
		('S485','Agency Fees'),
		('S490','Agency Fees'),
		('S492','Agency Fees'),
		('S495','Agency Fees'),
		('S500','Agency Fees'),
		('S501','Agency Fees'),
		('S504','Agency Fees'),
		('S505','Agency Fees'),
		('S510','Agency Fees'),
		('S514','Agency Fees'),
		('S515','Agency Fees'),
		('S519','Agency Fees'),
		('S520','Agency Fees'),
		('S522','Agency Fees'),
		('S524','Agency Fees'),
		('S525','Agency Fees'),
		('S530','Agency Fees'),
		('S540','Agency Fees'),
		('S543','Agency Fees'),
		('S545','Agency Fees'),
		('S550','Agency Fees'),
		('S555','Agency Fees'),
		('S560','Agency Fees'),
		('S561','Agency Fees'),
		('S564','Agency Fees'),
		('S565','Agency Fees'),
		('S570','Agency Fees'),
		('S573','Agency Fees'),
		('S580','Agency Fees'),
		('S582','Agency Fees'),
		('S590','Agency Fees'),
		('S592','Agency Fees'),
		('S600','Agency Fees'),
		('S605','Agency Fees'),
		('S610','Agency Fees'),
		('S611','Agency Fees'),
		('S620','Agency Fees'),
		('S621','Agency Fees'),
		('S630','Agency Fees'),
		('S640','Agency Fees'),
		('S650','Agency Fees'),
		('S655','Agency Fees'),
		('S660','Agency Fees'),
		('S662','Agency Fees'),
		('S665','Agency Fees'),
		('S670','Agency Fees'),
		('S672','Agency Fees'),
		('S680','Agency Fees'),
		('S681','Agency Fees'),
		('S685','Agency Fees'),
		('S690','Agency Fees'),
		('S700','Agency Fees'),
		('S702','Agency Fees'),
		('S703','Agency Fees'),
		('S709','Agency Fees'),
		('S710','Agency Fees'),
		('S711','Agency Fees'),
		('S720','Agency Fees'),
		('S722','Agency Fees'),
		('S723','Agency Fees'),
		('S730','Agency Fees'),
		('S735','Agency Fees'),
		('S740','Agency Fees'),
		('S741','Agency Fees'),
		('S743','Agency Fees'),
		('S750','Agency Fees'),
		('S760','Agency Fees'),
		('S761','Agency Fees'),
		('S762','Agency Fees'),
		('S764','Agency Fees'),
		('S765','Agency Fees'),
		('S770','Agency Fees'),
		('S780','Agency Fees'),
		('S782','Agency Fees'),
		('S785','Agency Fees'),
		('S790','Agency Fees'),
		('S800','Agency Fees'),
		('S801','Agency Fees'),
		('S804','Agency Fees'),
		('S810','Agency Fees'),
		('S811','Agency Fees'),
		('S814','Agency Fees'),
		('S815','Agency Fees'),
		('S820','Agency Fees'),
		('S830','Agency Fees'),
		('S840','Agency Fees'),
		('S842','Agency Fees'),
		('S843','Agency Fees'),
		('S850','Agency Fees'),
		('S855','Agency Fees'),
		('S860','Agency Fees'),
		('S861','Agency Fees'),
		('S865','Agency Fees'),
		('S880','Agency Fees'),
		('S890','Agency Fees'),
		('S900','Agency Fees'),
		('S903','Agency Fees'),
		('S910','Agency Fees'),
		('S912','Agency Fees'),
		('S915','Agency Fees'),
		('S920','Agency Fees'),
		('S921','Agency Fees'),
		('S923','Agency Fees'),
		('S950','Agency Fees'),
		('S951','Agency Fees'),
		('S959','Agency Fees'),
		('S960','Agency Fees'),
		('S961','Agency Fees'),
		('S962','Agency Fees'),
		('S964','Agency Fees'),
		('S970','Agency Fees'),
		('S981','Agency Fees'),
		('S999','Agency Fees'),
		
	/*courtfees*/
		('NCCF','Court Fees'),
		('NCCG','Court Fees'),
		('NCCH','Court Fees'),
		('NCCI','Court Fees'),
		('NCCJ','Court Fees'),
		('NCCK','Court Fees'),
		('NCCL','Court Fees'),
		('NHNU','Court Fees'),
	/*Jeffereson Davis Stat Fee-LA*/
		('LAND','Court Fees'),
		
		/*Statutory section*/
		('CANH','Court Fees'),
		('CANP','Court Fees'),
		('CANS','Court Fees'),
		('CANX','Court Fees'),
		('CAOA','Court Fees'),
		('CAOC','Court Fees'),
		('CAOH','Court Fees'),
		('CAOM','Court Fees'),
		('CAOS','Court Fees'),
		('CAOU','Court Fees'),
		('CAPC','Court Fees'),
		('CONA','Court Fees'),
		('CONB','Court Fees'),
		('FLOI','Court Fees'),
		('FLOL','Court Fees'),
		('ILNJ','Court Fees'),
		('KSND','Court Fees'),
		('LANA','Court Fees'),
		('LANB','Court Fees'),
		('MINC','Court Fees'),
		('MINH','Court Fees'),
		('MINN','Court Fees'),
		('MINS','Court Fees'),
		('MINT','Court Fees'),
		('MINW','Court Fees'),
		('MINX','Court Fees'),
		('MINY','Court Fees'),
		('MIOA','Court Fees'),
		('MIOB','Court Fees'),
		('MIOF','Court Fees'),
		('MIOI','Court Fees'),
		('MIOJ','Court Fees'),
		('MIOL','Court Fees'),
		('MIOR','Court Fees'),
		('MIOT','Court Fees'),
		('MIOZ','Court Fees'),
		('MIPA','Court Fees'),
		('MIPB','Court Fees'),
		('MIPC','Court Fees'),
		('MIPE','Court Fees'),
		('MIPF','Court Fees'),
		('MIPI','Court Fees'),
		('MIPJ','Court Fees'),
		('MIPK','Court Fees'),
		('MIPN','Court Fees'),
		('MIPU','Court Fees'),
		('MIPW','Court Fees'),
		('MIPX','Court Fees'),
		('MIPY','Court Fees'),
		('MIQE','Court Fees'),
		('MIQH','Court Fees'),
		('MIQJ','Court Fees'),
		('MIQK','Court Fees'),
		('MIQL','Court Fees'),
		('MIQS','Court Fees'),
		('MIQV','Court Fees'),
		('MIQW','Court Fees'),
		('MIQZ','Court Fees'),
		('MIRE','Court Fees'),
		('MIRH','Court Fees'),
		('MIRM','Court Fees'),
		('MIRN','Court Fees'),
		('MISM','Court Fees'),
		('MITA','Court Fees'),
		('MITD','Court Fees'),
		('MITJ','Court Fees'),
		('MITN','Court Fees'),
		('MONA','Court Fees'),
		('MSNG','Court Fees'),
		('MSNN','Court Fees'),
		('MSNQ','Court Fees'),
		('MSNX','Court Fees'),
		('MSOA','Court Fees'),
		('MTOH','Court Fees'),
		('NDNU','Court Fees'),
		('NHNG','Court Fees'),
		('NHNP','Court Fees'),
		('NHNR','Court Fees'),
		('NHOA','Court Fees'),
		('NVNA','Court Fees'),
		('NVNB','Court Fees'),
		('NVNC','Court Fees'),
		('NVNF','Court Fees'),
		('NVNG','Court Fees'),
		('NYNJ','Court Fees'),
		('NYNK','Court Fees'),
		('NYOH','Court Fees'),
		('NYOY','Court Fees'),
		('NYPC','Court Fees'),
		('NYPR','Court Fees'),
		('NYPV','Court Fees'),
		('NYPY','Court Fees'),
		('SCOH','Court Fees'),
		('SCOI','Court Fees'),
		('SCOJ','Court Fees'),
		('SCOK','Court Fees'),
		('SCOL','Court Fees'),
		('SDNA','Court Fees'),
		('TNNA','Court Fees'),
		('TNNB','Court Fees'),
		('TNNC','Court Fees'),
		('TNNF','Court Fees'),
		('TNNI','Court Fees'),
		('TNNJ','Court Fees'),
		('TNNM','Court Fees'),
		('TNNU','Court Fees'),
		('TNNW','Court Fees'),
		('TNNX','Court Fees'),
		('VTNA','Court Fees'),
		('VTNB','Court Fees'),
		('VTNC','Court Fees'),
		('VTND','Court Fees'),
		('VTNE','Court Fees'),
		('VTNJ','Court Fees'),
		('VTNK','Court Fees'),
		('VTNL','Court Fees'),
		('VTNN','Court Fees'),
		('VTNP','Court Fees'),
		('WYNC','Court Fees'),
		('WYNF','Court Fees'),
		('WYNH','Court Fees'),
		('WYNJ','Court Fees'),
		('WYNN','Court Fees'),
		('WYNO','Court Fees'),
		('WYNQ','Court Fees'),
		('WYNS','Court Fees'),
		('WYNU','Court Fees'),
		('WYNV','Court Fees'),
		('WYNX','Court Fees'),
		('WYNZ','Court Fees'),
		('WYOA','Court Fees'),
		('WYOD','Court Fees'),
		('WYOE','Court Fees'),
		('WYOH','Court Fees'),
		('WYOJ','Court Fees'),
		('WYOL','Court Fees'),
		('WYOM','Court Fees'),
		('WYOQ','Court Fees'),
		('WYOS','Court Fees'),
		('WYOU','Court Fees'),
	/*DRIVER INFORMATION*/
		('DI01','Driver History'),
		('DI02','Driver History'),
		('DI03','Driver History'),
	/*Statutory*/
		('SCOK','Court Fees'),
		('SCOL','Court Fees'),

	/*Court Fees*/
		('WYNA','Court Fees'),
		('WYNB','Court Fees'),
		('MINB','Court Fees'),
		('MIND','Court Fees'),
		('MENA','Court Fees'),
		('MENB','Court Fees'),
		('MENE','Court Fees'),
		('AZNM','Court Fees'),
		('MENG','Court Fees'),
		('MENH','Court Fees'),
		('MENI','Court Fees'),
		('MENJ','Court Fees'),
		('MENK','Court Fees'),
		('MINO','Court Fees'),
		('MINQ','Court Fees'),
		('VAKT','Court Fees'),
		('NHNA','Court Fees'),
		('NHNB','Court Fees'),
		('NHNC','Court Fees'),
		('NHND','Court Fees'),
		('WAAO','Court Fees'),
		('WYND','Court Fees'),
		('WYNE','Court Fees'),
		('VAKS','Court Fees'),
		('SDNJ','Court Fees'),
		('SDNK','Court Fees'),
		('VAKO','Court Fees'),
		('WYNI','Court Fees'),
		('NHNE','Court Fees'),
		('NHNF','Court Fees'),
		('MIOG','Court Fees'),
		('NHNH','Court Fees'),
		('NHNI','Court Fees'),
		('NHNJ','Court Fees'),
		('MIOK','Court Fees'),
		('SDNX','Court Fees'),
		('SDNY','Court Fees'),
		('AZNN','Court Fees'),
		('AZNO','Court Fees'),
		('SDOB','Court Fees'),
		('SDOC','Court Fees'),
		('WYNK','Court Fees'),
		('WYNL','Court Fees'),
		('NHNK','Court Fees'),
		('NHNL','Court Fees'),
		('NHNM','Court Fees'),
		('VAKR','Court Fees'),
		('ARNA','Court Fees'),
		('INNA','Court Fees'),
		('MIOP','Court Fees'),
		('ARNC','Court Fees'),
		('MENM','Court Fees'),
		('MENP','Court Fees'),
		('MENQ','Court Fees'),
		('SDOH','Court Fees'),
		('SDOI','Court Fees'),
		('SDOJ','Court Fees'),
		('SDOK','Court Fees'),
		('MIOU','Court Fees'),
		('NVNH','Court Fees'),
		('NVNI','Court Fees'),
		('NVNJ','Court Fees'),
		('SDOT','Court Fees'),
		('SDOU','Court Fees'),
		('MTNK','Court Fees'),
		('WAAP','Court Fees'),
		('MENV','Court Fees'),
		('MENW','Court Fees'),
		('FLNG','Court Fees'),
		('WYNP','Court Fees'),
		('NHNN','Court Fees'),
		('NHNO','Court Fees'),
		('MEOC','Court Fees'),
		('FLNN','Court Fees'),
		('NHNQ','Court Fees'),
		('WYNR','Court Fees'),
		('MIPM','Court Fees'),
		('NVNL','Court Fees'),
		('CANR','Court Fees'),
		('ARND','Court Fees'),
		('FLNQ','Court Fees'),
		('MIQG','Court Fees'),
		('MEOE','Court Fees'),
		('MEOF','Court Fees'),
		('MEOJ','Court Fees'),
		('CANT','Court Fees'),
		('CANU','Court Fees'),
		('MIQM','Court Fees'),
		('MIQN','Court Fees'),
		('MEOK','Court Fees'),
		('MEOL','Court Fees'),
		('MEOO','Court Fees'),
		('CANW','Court Fees'),
		('CANZ','Court Fees'),
		('MEOQ','Court Fees'),
		('MEOR','Court Fees'),
		('WYNW','Court Fees'),
		('NVNN','Court Fees'),
		('MIQX','Court Fees'),
		('FLNU','Court Fees'),
		('NYOF','Court Fees'),
		('MIRB','Court Fees'),
		('MIRF','Court Fees'),
		('MIRG','Court Fees'),
		('SDQI','Court Fees'),
		('MIRL','Court Fees'),
		('NHNS','Court Fees'),
		('NHNT','Court Fees'),
		('COSO','Court Fees'),
		('MIRQ','Court Fees'),
		('SDQT','Court Fees'),
		('SDQU','Court Fees'),
		('MIRT','Court Fees'),
		('COSN','Court Fees'),
		('CAOL','Court Fees'),
		('MIRV','Court Fees'),
		('MIRX','Court Fees'),
		('WYNY','Court Fees'),
		('NVNO','Court Fees'),
		('NYOQ','Court Fees'),
		('KSQT','Court Fees'),
		('MISO','Court Fees'),
		('MEOW','Court Fees'),
		('MEOX','Court Fees'),
		('MEOZ','Court Fees'),
		('WYOC','Court Fees'),
		('SDQX','Court Fees'),
		('SDQY','Court Fees'),
		('MEPB','Court Fees'),
		('MEPE','Court Fees'),
		('MEPG','Court Fees'),
		('MEPK','Court Fees'),
		('CAOO','Court Fees'),
		('CAOP','Court Fees'),
		('MISR','Court Fees'),
		('MTNV','Court Fees'),
		('VAKP','Court Fees'),
		('NHNV','Court Fees'),
		('NHNW','Court Fees'),
		('NHNX','Court Fees'),
		('MIST','Court Fees'),
		('MEPQ','Court Fees'),
		('MISX','Court Fees'),
		('MISZ','Court Fees'),
		('MITB','Court Fees'),
		('SDRH','Court Fees'),
		('SDRI','Court Fees'),
		('WYOG','Court Fees'),
		('CAQ5','Court Fees'),
		('CAOV','Court Fees'),
		('CAOW','Court Fees'),
		('MEPW','Court Fees'),
		('ARNF','Court Fees'),
		('VAKQ','Court Fees'),
		('NHNY','Court Fees'),
		('NHNZ','Court Fees'),
		('WYOI','Court Fees'),
		('NHOD','Court Fees'),
		('WYOK','Court Fees'),
		('FLOH','Court Fees'),
		('WYOP','Court Fees'),
		('ARNG','Court Fees'),
		('MITL','Court Fees'),
		('MEPY','Court Fees'),
		('MEQC','Court Fees'),
		('WYOR','Court Fees'),
		('MEQE','Court Fees'),
		('NVNR','Court Fees'),
		('ARNH','Court Fees'),
		('NYQB','Court Fees'),
		('VAKU','Court Fees'),
		('CAPE','Court Fees'),
		('MEQM','Court Fees'),
		('MEQQ','Court Fees'),	
	/*	profile*/
		('BPR1','People'),
	/*Address Search*/
		('BAD1','People'),
		('IAD1','People'),
		('INA1','People'),
		('BNA1','People'),
	/*DEMOGRAPHICS*/
		('DEM1','People'),
		
	/*Directory Assistance*/
		('BDA1','Directory Assistance'),
		('IDA1','Directory Assistance'),
	/*name/search/neighbors*/
		('BNC1','Directory Assistance'),
		('BNM1','Directory Assistance'),
		('BNS1','Directory Assistance'),
		('INC1','Directory Assistance'),
		('INM1','Directory Assistance'),
		('INS1','Directory Assistance'),
		('INA1','Directory Assistance'),
		('BNA1','Directory Assistance'),
		('BNE1','Directory Assistance'),
		('INE1','Directory Assistance'),
	/*phone search and verify*/
		('BTS1','Directory Assistance'),
		('ITS1','Directory Assistance'),
	/*Single County Civ. Search-OK*/
		('OKAF','Criminal Records'),
	/*inmate*/
		('COAD','Criminal Records'),
		('HIAD','Criminal Records'),
		('MDAD','Criminal Records'),
		('VTAC','Criminal Records'),
		('ILAE','Criminal Records'),
		('KSAD','Criminal Records'),
		('MIAF','Criminal Records'),
		('MSAE','Criminal Records'),
		('SCAD','Criminal Records'),
		('ALAD','Criminal Records'),
		('ARAI','Criminal Records'),
		('CAAE','Criminal Records'),
		('IAAE','Criminal Records'),
		('KSAE','Criminal Records'),
		('NCAD','Criminal Records'),
		('NEAD','Criminal Records'),
		('NJAD','Criminal Records'),
		('NMAD','Criminal Records'),
		('NVAC','Criminal Records'),
		('NYAD','Criminal Records'),
		('PAAD','Criminal Records'),
		('SCAE','Criminal Records'),
		('SDAD','Criminal Records'),
		('TNAE','Criminal Records'),
		('ABAE','Criminal Records'),
	/*CRIMINAL RECORDS*/
		('CR01','Criminal Records'),
	/*VEHICLE INFORMATION*/
		('VI01','Vehicle Data'),
		('VI02','Vehicle Data'),
		('VI03','Vehicle Data'),
	/*judgements*/
		('JD01','Assets'),
		('IAA6','Assets'),
		('IAA5','Assets'),
	/*bankrump*/
		('BK01','Assets'),
	/*REAL ESTATE*/
		('RE01','Assets'),
	/*TAX LIENS*/
		('TX01','Assets'),
	/*UCC FILINGS*/
		('UCC1','Business'),
	/*Explicit Other*/
		('CH00','Other'),
		('CH01','Other'),
		('CH02','Other'),
		('CH03','Other'),
		('CH04','Other'),
		('CH05','Other'),
		('CH06','Other'),
		('CH07','Other'),
		('CH08','Other'),
		('CH10','Other'),
		('QIQ1','Other'),
		('QNQ1','Other'),
		('Q1UC','Other'),
		('MUQ1','Other'),
		('0002','Other'),
		('QIQ2','Other'),
		('QNQ2','Other'),
		('Q2UC','Other'),
		('MUQ2','Other'),
		('0003','Other'),
		('QIQ3','Other'),
		('QNQ3','Other'),
		('Q3UC','Other'),
		('MUQ3','Other'),
		('0004','Other'),
		('QIQ4','Other'),
		('QNQ4','Other'),
		('Q4UC','Other'),
		('MUQ4','Other'),
		('0005','Other'),
		('LAAR','Other'),
		('LCAR','Other'),
		('LPAR','Other'),
		('AFEE','Other'),
		('0006','Other'),
		('LA09','Other'),
		('LA10','Other'),
		('LA11','Other'),
		('LA01','Other'),
		('LA02','Other'),
		('LA03','Other'),
		('LA04','Other'),
		('LA05','Other'),
		('LA06','Other'),
		('LA07','Other'),
		('LA08','Other'),
		('LCMB','Other'),
		('LC09','Other'),
		('LC10','Other'),
		('LC11','Other'),
		('LC01','Other'),
		('LC02','Other'),
		('LC03','Other'),
		('LC04','Other'),
		('LC05','Other'),
		('LC06','Other'),
		('LC07','Other'),
		('LC08','Other'),
		('ICA1','Other'),
		('LAAF','Other'),
		('LCAF','Other'),
		('LPAF','Other'),
		('QIDM','Other'),
		('QNAM','Other'),
		('MFEE','Other'),
		('0007','Other'),
		('0001','Other'),
		('0013','Other'),
		('LP09','Other'),
		('LP10','Other'),
		('LP11','Other'),
		('LP02','Other'),
		('LP03','Other'),
		('LP04','Other'),
		('LP05','Other'),
		('LP06','Other'),
		('LP07','Other'),
		('LP08','Other'),
		('TRAN','Other'),
		('MUFC','Other'),
		('MUFM','Other'),
	/*proflic*/
		('PL01','People'),
		('0011','Vehicle Data'),
		('PRB1','Append-DS')
	) AS ProductHierarchyUpdateSet (productTransactionCode, productHierarchyValue)		

SELECT *
FROM
	DecisionNet.ProductHierarchy
	INNER JOIN #ProductHierarchyUpdateSet
		ON ProductHierarchy.productTransactionCode = #ProductHierarchyUpdateSet.productTransactionCode;

UPDATE DecisionNet.ProductHierarchy
SET
	ProductHierarchy.productHierarchyLvl1 = ISNULL(ProductHierarchy.productHierarchyLvl1,#ProductHierarchyUpdateSet.productHierarchyValue),
	ProductHierarchy.productHierarchyLvl2 = #ProductHierarchyUpdateSet.productHierarchyValue,
	ProductHierarchy.productHierarchyLvl3 = ISNULL(ProductHierarchy.productHierarchyLvl3,#ProductHierarchyUpdateSet.productHierarchyValue),
	ProductHierarchy.dateInserted = @dateInserted
FROM
	#ProductHierarchyUpdateSet
WHERE
	ProductHierarchy.productTransactionCode = #ProductHierarchyUpdateSet.productTransactionCode

INSERT INTO DecisionNet.ProductHierarchy
(
	productTransactionCode,
	productTransactionDescription,
	productTransactionCodeRemap,
	productHierarchyLvl1,
	productHierarchyLvl2,
	productHierarchyLvl3,
	dateInserted
)
SELECT
	#ProductHierarchyUpdateSet.productTransactionCode,
	Product.productTransactionDescription,
	NULL AS	productTransactionCodeRemap,
	#ProductHierarchyUpdateSet.productHierarchyValue AS productHierarchyLvl1,
	#ProductHierarchyUpdateSet.productHierarchyValue AS productHierarchyLvl2,
	#ProductHierarchyUpdateSet.productHierarchyValue AS productHierarchyLvl3,
	@dateInserted AS dateInserted
FROM
	#ProductHierarchyUpdateSet
	INNER JOIN DecisionNet.Product
		ON Product.productTransactionCode = #ProductHierarchyUpdateSet.productTransactionCode
WHERE
	NOT EXISTS
	(
		SELECT NULL
		FROM
			DecisionNet.ProductHierarchy
		WHERE
			ProductHierarchy.productTransactionCode = #ProductHierarchyUpdateSet.productTransactionCode
	);
	
SELECT *
FROM
	DecisionNet.ProductHierarchy
	INNER JOIN #ProductHierarchyUpdateSet
		ON ProductHierarchy.productTransactionCode = #ProductHierarchyUpdateSet.productTransactionCode;
	
PRINT 'ROLLBACK TRANSACTION';ROLLBACK TRANSACTION;
--PRINT 'COMMIT TRANSACTION';COMMIT TRANSACTION;

/*
EXEC in claimsearch 20180928
(13 row(s) affected)

(9 row(s) affected)

(4 row(s) affected)

(17 row(s) affected)

(1817 row(s) affected)

(1008 row(s) affected)

(1008 row(s) affected)

(807 row(s) affected)

(1815 row(s) affected)
COMMIT TRANSACTION

*/